// v66: Diseño Pro — own visual page builder backend. Pages can be full custom
// HTML/CSS (mode 'html'): persisted, publicly rendered with SEO + lead-form
// wiring, generated by AI (template fallback) and still capture leads.
const { test, before } = require('node:test');
const assert = require('node:assert');

process.env.NODE_ENV = 'test';
delete process.env.ANTHROPIC_API_KEY;

const request = require('supertest');
const app = require('../server/index');

let H, funnelId, pageId, funnelSlug, pageSlug;

before(async () => {
  const r = await request(app).post('/api/auth/register').send({
    agency_name: 'Pro', name: 'A', email: 'pro@test.com', password: 'secret1', location_name: 'Sede',
  });
  const me = await request(app).get('/api/auth/me').set('Authorization', `Bearer ${r.body.token}`);
  H = { Authorization: `Bearer ${r.body.token}`, 'X-Location-Id': String(me.body.locations[0].id) };
  const f = await request(app).post('/api/funnels').set(H).send({ name: 'Pro Funnel' });
  funnelId = f.body.id;
  funnelSlug = f.body.slug;
  pageId = f.body.pages[0].id;
  pageSlug = f.body.pages[0].slug;
});

test('a page persists custom HTML/CSS in Pro mode', async () => {
  const res = await request(app).put(`/api/funnels/${funnelId}/pages/${pageId}`).set(H).send({
    mode: 'html',
    html_raw: '<section class="lp-hero"><h1>Página a medida</h1></section><form data-lead data-success="Gracias"><input name="email"><button>Enviar</button></form>',
    css_raw: '.lp-hero{background:#111}',
    published: true,
    content: [],
  });
  assert.equal(res.status, 200);
  assert.equal(res.body.mode, 'html');
  assert.match(res.body.html_raw, /Página a medida/);
});

test('the public page renders the raw design with SEO wrap and lead wiring', async () => {
  const page = await request(app).get(`/f/${funnelSlug}/${pageSlug}`);
  assert.equal(page.status, 200);
  assert.match(page.text, /Página a medida/, 'custom HTML served');
  assert.match(page.text, /\.lp-hero\{background:#111\}/, 'custom CSS injected');
  assert.match(page.text, /form\[data-lead\]/, 'lead-capture wiring script injected');
  assert.match(page.text, new RegExp(`/api/public/pages/${pageId}/submit`), 'form posts to the CRM');
});

test('a lead submitted from a Pro page lands in the CRM', async () => {
  const res = await request(app).post(`/api/public/pages/${pageId}/submit`).send({
    first_name: 'ProLead', email: 'prolead@x.com',
  });
  assert.equal([200, 201].includes(res.status), true);
  const contacts = await request(app).get('/api/contacts').set(H);
  assert.ok(contacts.body.some((c) => c.email === 'prolead@x.com'), 'lead captured from the Pro page');
});

test('AI landing generator (fallback) produces a full page with a capture form', async () => {
  const res = await request(app).post('/api/ai/landing-html').set(H).send({
    funnel_id: funnelId, page_id: pageId, prompt: 'Landing para clínica dental con oferta de blanqueamiento',
  });
  assert.equal(res.status, 200);
  assert.match(res.body.generated_by, /template/);
  assert.match(res.body.html, /data-lead/, 'generated page always includes a capture form');
  assert.ok(res.body.css.length > 100, 'stylesheet generated');
  // Persisted onto the page in html mode.
  const page = await request(app).get(`/f/${funnelSlug}/${pageSlug}`);
  assert.match(page.text, /data-lead/);
});

test('design chat on a Pro page answers gracefully without an AI key', async () => {
  const res = await request(app).post('/api/ai/design').set(H).send({
    funnel_id: funnelId, page_id: pageId, prompt: 'hazla más oscura',
  });
  assert.equal(res.status, 200);
  assert.equal(res.body.mode, 'html');
  assert.equal(res.body.changed, false, 'no silent edits without AI');
  assert.match(res.body.reply, /IA|API key/i);
});

test('the builder preview renders Pro pages too', async () => {
  const prev = await request(app).get(`/api/funnels/${funnelId}/pages/${pageId}/preview`).set(H);
  assert.equal(prev.status, 200);
  assert.match(prev.text, /data-lead/);
});
